---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snapserver-${spotify_user.name}
  namespace: snapserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
