---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snapserver-${cert_manager_cloudflare_dns_secret_name_prefix}
  namespace: snapserver
spec:
  secretName: snapserver-${cert_manager_cloudflare_dns_secret_name_prefix}-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "snapserver.${cert_manager_cloudflare_dns_zone}"
  dnsNames:
    - "snapserver.${cert_manager_cloudflare_dns_zone}"
